tango_with_django_project/rango/urls.py
#!/usr/bin/env python
#-*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name='rango'

urlpatterns=[
    url(r'^about/$',views.about,name='about'),
    url(r'^$',views.index,name='index'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',views.show_category,name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',views.add_page,name='add_page'),
    url(r'^add_category/$',views.add_category,name='add_category'),
    # url(r'^register/$',views.register,name='register'),
    # url(r'^login/$',views.user_login,name='login'),
    url(r'^restricted/$',views.restricted,name='restricted'),
    # url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^goto/$',views.track_url,name='goto'),
    url(r'^profile_register/$',views.profile_register,name='profile_register'),
    url(r'^profile/(?P<username>[\w\-]+)/$',views.profile,name='profile'),
    url(r'^list_profiles/$',views.list_profiles,name='list_profiles'),
    url(r'^like/$',views.like_category,name='like_category'),
    url(r'^suggest/$',views.suggest_category,name='suggest_category')
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from rango import views

from registration.backends.simple.views import RegistrationView
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user=None):
        return '/rango/profile_register'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rango/',include('rango.urls')),
    url(r'^accounts/register/$',MyRegistrationView.as_view(),name='registration_register'),
    url(r'^accounts/',include('registration.backends.simple.urls')),
    url(r'^$',views.index,name='index_1')
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
class Category(models.Model):
    name = models.CharField(max_length=128,unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug=models.SlugField(unique=True)

    def save(self,*args,**kw):
        self.slug=slugify(self.name)
        super(Category,self).save(*args,**kw)

    class Meta:
        #指定复数形式
        verbose_name_plural='Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category=models.ForeignKey(Category)
    title=models.CharField(max_length=128)
    url=models.URLField()
    views=models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user=models.OneToOneField(User)

    website=models.URLField(blank=True)
    picture=models.ImageField(blank=True,upload_to='profile_images')

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
#!/usr/bin/env python
#-*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from .models import Category,Page,UserProfile

class CategoryForm(forms.ModelForm):
    name=forms.CharField(max_length=128,help_text="请输入category的name")
    views=forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug=forms.CharField(widget=forms.HiddenInput(),required=False)

    class Meta:
        model=Category
        fields=('name',)

class PageForm(forms.ModelForm):

    def clean(self):
        clean_data=self.cleaned_data
        url=clean_data.get('url')

        if url and not url.startswith('http://'):
            url='http://'+url
            clean_data['url']=url
        return clean_data

    title=forms.CharField(max_length=128,help_text='请输入page的title')
    url=forms.URLField(max_length=200,help_text='请输入page的url')
    views=forms.IntegerField(widget=forms.HiddenInput(),initial=0)

    class Meta:
        model=Page
        exclude=('category',)

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username','email','password')

class UserProfileForm(forms.ModelForm):

    website=forms.URLField(required=False)
    picture=forms.ImageField(required=False)

    class Meta:
        model=UserProfile
        fields=('website','picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Category,Page,UserProfile
from .forms import PageForm,CategoryForm,UserForm,UserProfileForm
from datetime import datetime

def visitor_cookie_handler(request):
    visits=int(request.session.get('visits','1'))
    last_visit_cookie=request.session.get('last_visit',str(datetime.now()))
    last_visit_time=datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now()-last_visit_time).seconds>60:
        visits+=1
        request.session['last_visit']=str(datetime.now())
    else:
        request.session['last_visit'] =last_visit_cookie

    request.session['visits']=visits

def index(request):
    # request.session.set_test_cookie()
    category_list_liked=Category.objects.order_by('-likes')[:5]
    page_list_viewed=Page.objects.order_by('-views')[:5]
    con_dict={'categories_liked':category_list_liked,'page_list_viewed':page_list_viewed}

    visitor_cookie_handler(request)
    con_dict['visits']=request.session['visits']

    response = render(request, 'rango/index.html', context=con_dict)
    return  response

def show_category(request,category_name_slug):
    con_dict={}
    try:
        category=Category.objects.get(slug=category_name_slug)
        pages=Page.objects.filter(category=category)
        con_dict["pages"]=pages
        con_dict["category"] = category

    except Category.DoesNotExist:

        con_dict["pages"] = None
        con_dict["category"] = None
    return render(request,'rango/category.html',con_dict)

@login_required
def add_category(request):
    form=CategoryForm()
    if request.method=='POST':
        form=CategoryForm(request.POST)
        if form.is_valid():
            cat=form.save(commit=True)
            print(cat,cat.slug)
            return index(request)
        else:
            print(form.errors)
    return render(request,'rango/add_category.html',{'form':form})

@login_required
def add_page(request,category_name_slug):

    try:
        category=Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category=None

    form = PageForm()
    if request.method=='POST':
        form=PageForm(request.POST)
        if form.is_valid():
            if category is not None:
                print(category)
                page=form.save(commit=False)
                page.category=category
                page.views=0
                page.save()
                print('save successfully')
            return show_category(request,category_name_slug)
        else:
            print(form.errors)

    return render(request,'rango/add_page.html',{'form':form,'category':category})


# def register(request):
#
#     registered=False
#
#     if request.method=='POST':
#         user_form=UserForm(data=request.POST)
#         profile_form=UserProfileForm(data=request.POST)
#         if user_form.is_valid() and profile_form.is_valid():
#             user=user_form.save()
#
#             user.set_password(user.password)
#             user.save()
#
#             profile=profile_form.save(commit=False)
#             profile.user=user
#
#             if 'picture' in request.FILES:
#                 profile.picture=request.FILES['picture']
#
#             profile.save()
#             registered=True
#         else:
#             print(user_form.errors,profile_form.errors)
#     else:
#         user_form = UserForm()
#         profile_form = UserProfileForm()
#
#     return render(request,'rango/register.html',
#                   {'user_form':user_form,'profile_form':profile_form,'registered':registered})
#
# def user_login(request):
#     if request.method=='POST':
#         username=request.POST.get('username')
#         password=request.POST.get('password')
#         user=authenticate(username=username,password=password)
#         if user:
#             if user.is_active:
#                 login(request,user)
#                 print('登录成功')
#                 return HttpResponseRedirect(reverse('rango:index'))
#             else:
#                 return HttpResponse("账户不可用！")
#         else:
#             print('无效的登录信息，{0}，{1}'.format(username,password))
#             return HttpResponse("无效的登录信息！")
#     else:
#         return render(request,'rango/login.html',{})

@login_required
def restricted(request):
    return HttpResponse("如果你登录了，你就能看见这段话！")

# @login_required
# def user_logout(request):
#     logout(request)
#  return HttpResponseRedirect(reverse('rango:index'))

def about(request):
    # if request.session.test_cookie_worked():
    #     print('TEST COOKIE WORKED!')
    #     request.session.delete_test_cookie()
    visitor_cookie_handler(request)
    visits=request.session.get('visits')
    return  render(request,'rango/about.html',{'visits':visits})

def track_url(request):
    page_id=None
    if request.method=='GET':
        if 'page_id' in request.GET:
            page_id=request.GET['page_id']
    if page_id:
        try:
            page=Page.objects.get(id=page_id)
            page.views=page.views+1
            page.save()
            return redirect(page.url)
        except:
            return HttpResponseRedirect("page id : {} is not found.".format(page_id))
    print('no page_id in get string')
    return redirect(reverse('rango:index'))

@login_required
def profile_register(request):
    form=UserProfileForm()
    if request.method=='POST':
        form=UserProfileForm(request.POST,request.FILES)
        if form.is_valid():
            user_profile=form.save(commit=False)
            user_profile.user=request.user
            user_profile.save()
            return redirect('rango:index')
        else:
            print(form.errors)
    return render(request,'rango/profile_registration.html',{'form':form})

@login_required
def profile(request,username):
    try:
        user=User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('rango:index')

    userprofile=UserProfile.objects.get_or_create(user=user)[0]
    form=UserProfileForm({'website':userprofile.website,'picture':userprofile.picture})

    if request.method=='POST':
        form=UserProfileForm(request.POST,request.FILES,instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile',user.username)
        else:
            print(form.errors)

    return render(request,'rango/profile.html',{'userprofile':userprofile,'selecteduser':user,'form':form})

@login_required
def list_profiles(request):
    userprofile_list=UserProfile.objects.all()
    return render(request,'rango/list_profiles.html',{'userprofile_list':userprofile_list})

@login_required
def like_category(request):
    cat_id=None
    if request.method=='GET':
        cat_id=request.GET['category_id']
    likes=0
    if cat_id:
        cat=Category.objects.get(id=int(cat_id))
        if cat:
            likes=cat.likes+1
            cat.likes=likes
            cat.save()
    return HttpResponse(likes)

def get_category_list(max_result=0,starts_with=''):
    cat_list=[]
    if starts_with:
        cat_list=Category.objects.filter(name__istartswith=starts_with)

    if max_result>0:
        if len(cat_list)>max_result:
            cat_list=cat_list[:max_result]

    return cat_list

def suggest_category(request):
    cat_list=[]
    starts_with=''
    if request.method=='GET':
        starts_with=request.GET['suggestion']
    cat_list=get_category_list(8,starts_with)

    return render(request,'rango/cats.html',{'cats':cat_list})

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base_bootstrap.html'%}
{% load staticfiles %}

{% block title_block %}
About
{% endblock %}

{% block body_block %}
<h1>This is a About Page!</h1>
Visits:{{visits}}
<h4>This tutorial has been put together by huu.</h4><br>
<img src="{% static 'images/huaji.jpg'%}" alt="picture is gone"><br>
<img src="{{MEDIA_URL}}dora.jpg" alt="picture is gone">
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base_bootstrap.html'%}
{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title_block %}
add_category
{% endblock %}

{% block body_block %}


    <form id="category_form" method="post" action="{% url 'rango:add_category' %}" >
        <h2 class="form-signin-heading">Add a Category</h2>
        {% csrf_token %}
        {{ form|as_bootstrap }}
        <br>
        <button class="btn btn-primary" type="submit" name="submit">Add a Category</button>
    </form>
</div>

{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base_bootstrap.html'%}
{% load staticfiles %}

{% block title_block %}
add_page
{% endblock %}

{% block body_block %}
{% if category%}

<div>
    <link href="http://v4-alpha.getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
    <br>
    <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug%}">
        <h2 class="form-signin-heading">Add a Page to <a href="/rango/category/{{category.slug}}">{{category.name}}</a></h2>
        {% csrf_token %}

        {% for hidden in form.hidden_fields%}
            {{hidden}}
        {% endfor %}
        {% for field in form.visible_fields%}
            {{field.errors}}
            {{field.help_text}}<br>
            {{field}}<br>
        {% endfor %}
        <br>
        <button class="btn btn-primary" type="submit" name="submit">Add a Page</button>
    </form>
</div>
{% else %}
<p>这个category 不存在！</p>
{% endif %}
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango-
        {% block title_block %}
        Tango with Django
        {% endblock %}
    </title>
</head>
<body>
    <div style="border:1px black solid">
        {% block sidebar_block %}
            <i>sidebar</i>
            {% get_category_list category%}
        {% endblock %}
    </div>
    <div>
        {% block body_block %}
            This is default page!
        {% endblock %}
    </div>
    <hr>
    <div>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
            <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
            <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
            {% else %}
            <li><a href="{% url 'registration_register' %}">Sing Up</a></li>
            <li><a href="{% url 'auth_login' %}">Sign In</a></li>
            {% endif %}
            <hr>
            {% if user.is_authenticated %}
            <li><a href="{% url 'rango:add_category' %}">Add New Page</a></li>
            {% endif %}
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>

        </ul>
    </div>

</body>
</html>

tango_with_django_project/templates/rango/base_bootstrap.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load rango_template_tags %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

      <title>Rango - {% block title_block %}How to Tango with Django!{% endblock %}</title>
      <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand active" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
            </li>
        {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">

      <div class="col-sm-3 col-md-2 sidebar ">
          <ul class="nav nav-list">
              <li class="nav-header">Type to find a category</li>

              <form>
                  <li>
                      <input type="text" class="search-query form-control" name="suggestion" value="" id="suggestion">
                  </li>
              </form>
          </ul>
         <!--{% block sidebar_block %}-->
             <!--{% get_category_list category %}-->
         <!--{% endblock %}-->
          <hr>
          <div id="cats">

          </div>
      </div>


      <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
         {% block body_block %}
             {% get_category_list category %}
         {% endblock %}

        </div>
      </div>
    </div>

     <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
 <!--
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
 -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

    <script src="{% static 'js/rango-ajax.js' %}"></script>
    <!--<script src="{% static 'js/rango-jquery.js' %}"></script>-->
  </body>
</html>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base_bootstrap.html'%}
{% load staticfiles %}


{% block title_block %}
{{ category.name}}
{% endblock %}

{% block body_block %}
{% if category %}
    <h1>{{category.name}}</h1>
    <div>
    <strong id="like_count">{{category.likes}}</strong> people like this category
        {% if user.is_authenticated %}
        <button id="likes" data-catid="{{category.id}}" class="btn btn-primary btn-sm" type="button">
            Like
        </button>
        {% endif %}
    </div>
    <ul>{% if pages%}
            {% for page in pages %}
                <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{page.title}}</a>&nbsp;{{page.views}}</li>
            {% endfor %}
        {% endif %}
    </ul>
    {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug%}">Add a Page</a>
    {% endif %}
{% else %}
    <strong>这个分类中没有pages</strong>
{% endif %}
{% endblock %}

tango_with_django_project/templates/rango/cats.html
<ul class="flex-column">
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
            <strong>
                <i>
                    <li class="nav-item"><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
                </i>
            </strong>
            {% else %}
            <li class="nav-item"><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <strong>....</strong>
    {% endif %}
</ul>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base_bootstrap.html'%}
{% load staticfiles %}

{% block title_block %}
Index
{% endblock %}

{% block body_block %}

<div class="jumbotron">

<h1 class="display-3">Rango says...</h1>
<div>
    你好啊！<br>
    {% if user.is_authenticated %}
    howdy {{user.username}}
    {% else %}
    hi stranger!
    {% endif %}
</div>
</div>

<div class="row marketing">
<div class="col-lg-6">
    <h4>Most Liked Categories</h4>
    {% if categories_liked %}
    <ul class="list-group">
        {% for c in categories_liked%}
            <li class="list-group-item"><a href="{% url 'rango:show_category' c.slug %}">{{c.name}}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <strong>当前没有Category。</strong>
    {% endif %}
</div>


<div class="col-lg-6">
    <h4>Most Viewed Pages</h4>
        {% if page_list_viewed %}
        <ul class="list-group">
            {% for p in page_list_viewed%}
                <li class="list-group-item"><a href="{{ p.url }}">{{p.title}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>NO PAGES</strong>
        {% endif %}
</div>
</div>

<div>
    <img src="{% static 'images/huaji.jpg' %}" width="100" height="100" alt="picture of huaji">

</div>
{% endblock %}

tango_with_django_project/templates/rango/list_profiles.html
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}
{% block title_block %}
Users Profiles
{% endblock %}

{% block body_block %}
<h1>Users Profiles</h1>
<div class="panel">
    {% if  userprofile_list %}
    <div class="panel-heading">
        <div class="panel-body">
            <div class="list-group">
            {% for listuser in userprofile_list%}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <a href="{% url  'rango:profile' listuser.user.username %}">{{listuser.user.username}}</a>
                    </h4>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
    {% else %}
    <p>当前没有用户！</p>
    {% endif %}
</div>
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}
<form action="{% url 'rango:login' %}" method="post">
    {% csrf_token %}
    Username: <input type="text" name="username" value=""><br>
    Password: <input type="password" name="password" value=""><br>
    <input type="submit" value="login">
</form>
{% endblock %}

tango_with_django_project/templates/rango/profile.html
{% extends "rango/base_bootstrap.html" %}
{% block title_block %}
{{selecteduser.username}} Profile
{% endblock %}

{% block body_block %}
<h1>{{selecteduser.username}} Profile</h1>
<img src="{{MEDIA_URL}}{{userprofile.picture}}"
     width="300"
     height="300"
     alt="{{selecteduser.username}}">
<br>
<br>
{% if  selecteduser.username == user.username%}
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% else %}
Website:<p><strong>
    <a href="{{userprofile.url}}">{{userprofile.url}}</a>
    </strong></p>
{% endif %}

{% endblock %}

tango_with_django_project/templates/rango/profile_registration.html
{% extends "rango/base_bootstrap.html" %}
{% block title_block %}
Register - Step 2
{% endblock %}
{% block body_block %}
<h1>Register - Step 2</h1>
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends 'rango/base_bootstrap.html'%}
{% load staticfiles %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
    {% if registered %}
    注册成功！感谢！
    <a href="{% url 'rango:index' %}">返回主页</a><br>
    {% else %}
    在下面进行注册：

    <form action="{% url 'rango:register'%}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" name="submit" value="Register">
    </form>

    {% endif %}
{% endblock %}